ubports/crossbuilder

- crossbuilder
On Ubuntu 16.04, the lxdbr0 bridge is configured by default as
link-local only. This isn't very helpful when we want to connect
containers to the internet. This patch adds another step that configures
the bridge.
Fixes #11
> Workaround to configure lxd bridge on xenial

- crossbuilder
Add support for optionally providing a '--privileged' option.
Privileged containers are required for the Snap version of LXD to properly setup a working build environment.
In case a LXD Snap installation is detected privileged containers are used automatically.
> crossbuilder: Force privileged containers using --privileged option

- crossbuilder
Previously I got this:
```
dpkg-deb: error: parsing file 'tmp/DEBIAN/control' near line 21 package 'dh-systemd':
duplicate value for 'Multi-Arch' field
```
The script was not aware of the case of the letters of ```Multi-arch```.
> Fix Multi-Arch duplicate field

- crossbuilder
-) Pull dependencies by running mk-build-deps and installing them in the container, tested with telepathy-ofono
-) Add support for the ubports.source_location file to pull sources from the right place, tested with QtWebEngine
> crossbuilder: Support for mk-build-deps & ubports.source_location

- crossbuilder
The LXD binary has been replaced with a script telling you to install
the lxd snap in newer versions of Ubuntu. We need to handle the snap
version of lxd better.
These changes check for the LXD snap and work with it in a much more
comprehensive way. For example, we use 'snap restart' to manage the
service. I also had to add a ridiculous amount of checking for the
container's state since lxc may or may not return an error code if it
fails to start a container.
Fixes #26
> Updates for Snap support

- crossbuilder
This PR make the clean command starts the container before actually cleaning. However, as it's not worth it to create a brand-new container just to clean a potentially not-built folder, I've decided to refactor code to separate containers starting and creating apart so that I can decide to not create a container later.
>  Make sure the container is started before cleaning

- crossbuilder
This option set parallism of the build, which is helpful when you're
looking for the build failure, or the RAM of the computer is too small
for the default parallism when building some package.
> Add --parallel option

- crossbuilder
The code tries to detect the phrase "not found" printed when the shell
cannot find dpkg. However, such message is printed to stderr, not
stdout.
> Fix detecting non-Ubuntu device on ADB

- crossbuilder
This PR enables building & using .ddeb packages, which is useful when debugging software.
> Build, archive, and provide -dbgsym packages

- crossbuilder
When using the script crossbuilder in a localized environment, the script will not detect Status of the container.
> make sure script works in localized environment

- crossbuilder
This PR contains 2 improvements to crossbuilder dependencies installation.
The first one is the usage of --no-install-recommends in dependencies resolving. This helps reduce unnecessary dependencies. It also helps work around a bug in apt that causes it to remove packages for the sake of installing recommended packages.
The second one is the complete removal of source repository creation. Source package repository was used to allow "apt-get build-dep" to be used. However, now that we use mk-build-deps, there's no need to use source repository anymore.
> Improvements for dependencies installation

- crossbuilder
Commit 1cde99346a03c70f97f92eabf923f43960461f4e (install_dependencies:
don't create source package & repo anymore) removes the creation of the
"source repository". However, turns out this same repository is also
used in copying dependent builds into the container. This commit restore
the repo creation & addition part to copy_build_to_container function,
while improve it so that --allow-unauthenticated isn't required.
> copy_build_to_container: also create & add repo

- crossbuilder
Otherwise, `debian/rules` may depends on some build dependencies that
isn't installed in the build profiles we used to compute dependencies.
> Also include build profiles in clean command

- crossbuilder
The same technique is used on build-tools' build-source.sh to support
multiple tarball. Thus, if this script can pull the upstream tarball(s),
CI would be able to pull them.
Sees https://github.com/ubports/build-tools/commit/47279578ce3602d3843a14835d5dc074bd6c8504
> ensure_upstream_tarball: support multiple tarball

- crossbuilder
This allows packages using bare makefiles to call strip and a few other
tools directly.
> create_container: set CROSS_COMPILE env

- crossbuilder
The de-facto policy in Debian is to specify `QT_SELECT=qt5` in
debian/rules, therefore overriding the variable we set here. Since we
are not building for the host architecture anyway, let's set the qt5
profile to always cross-compile.
> crossbuilder: Setup the `qt5` profile for cross-compilation

- crossbuilder
If the old directory no longer exists, the container will fail to start.
Move the mount dir configuration before the container starts to prevent
container start failure.
> Config mount dir before start existing container

- crossbuilder
This PR contains a set of commits that allow me (and other people) to cross-build packages using the Focal base image and UBports' repository. This helps a lot when porting Ubuntu Touch to Ubuntu 20.04.
To cross-build for Ubuntu 20.04, one simply has to `--lxd-image=ubuntu:20.04` (along with the architecture). Crossbuilder will setup the container automatically.
This PR also contains an unrelated commit to switch GPG keyring downloading to HTTPS. Because it will conflict with another commit in this PR, I think it's easier to just include it in this PR.
> Make it possible to cross-build for focal

- crossbuilder
TARGET_UBUNTU is a command-line option intended to help choosing the lxd
image. If we specify our own image, this variable becomes useless.
Instead, run `lsb_release` in the container to get image's Ubuntu
version.
Also re-route bionic to repo instead of repo2. It's available there, and
repo should contains more packages as it allows packages that Aptly
(repo2) otherwise doesn't.
> nonsdk_container_setup: fix ubuntu version detection

- crossbuilder
It's not clear how cmake finds the `moc` tool, but for some reason it
expects to find it in `/usr/lib/$HOST_FARCH/qt5/bin/`. So, let's put it
there.
Also, rework a bit the way that qmake is setup, by using a more robust
approach that does not require the `QT_SELECT=qt5` trick: we simply
install qmake in `/usr/local/bin/`, just like `clickable` is doing.
Last but not least, correct the value of the `HOST_FARCH` variable,
which was computed wrong (it is used in this part of crossbuilder
anyway, so changing it should not bring any side-effects).
> crossbuilder: fix missing moc tool for cmake

- crossbuilder
These patches allow me to use crossbuilder with the Debian lxd image (namely, `images:debian/bullseye`). This allows me to do builds on Debian when Debian's package maintainer report a problem.
> Allow using Debian lxd images

- crossbuilder
Well, '-e' is not defined in /bin/sh. With it, every (colored) text
printed has '-e' prefix. Use /bin/bash instead.
> Use Bash as the intepreter

- crossbuilder
Apparently the output format of `lxc info` changed recently. To keep the
detection working, switch to JSON API and use jq to parse the result. Jq
is added as a requisite.
The commit is mentioned in #56.
> Replace some usage of `lxc info` to use JSON API

- crossbuilder
Most of the time we don't care about udeb; those are used for Debian
Installer. This essentially halves the build time when a package need
a separated build for udeb e.g. systemd.
> Add 'noudeb' to build profiles and options

- crossbuilder
- If no 'dpkg' command found, try to determine host architecture using
other metod(s).
- Don't check for 'dpkg-architecture' command at beginning. Run the
command in container, if missing.
- Don't check for 'dpkg-parsechangelog' command at beginning. Run the
command in container or replace it by using grep+sed, if missing.
- Run lxd daemon at startup, if not running.
- Use current user/group id in lxd subuid/subgid setup & assurance.
- If not 'apt' found, check for 'pacman' and use if present.
- If container is missing network access, try to apply 'dhclient' hack.
and then check again for network.
> Changes needed to use crossbuilder on manjaro

- README.md
- crossbuilder
This PR adds the ability to deploy via ssh.
I've splitted the PR into thematic commits for easier review.
- The first 6 commits (28a4ea0, ..., 7e1fd88) are refactoring changes, which moves all the ```adb``` commands in crossbuilder script into functions with a concrete goal (exec_device, push_device, ...), one ```adb``` type per commit.
- The 7th commit (9eddcb7) refactors the options parameter evaluation before the first ```adb``` command call (missing packages checks), to be able to not use adb if --ssh option is passed.
- The 8th commit (f27805e) is the actual ssh code logic.
- The last 2 commits (6c1dd34, 4ea693c) are documentation updates and a fix to be able to use --ssh with --no-deb option.
Note: This solves #42 and #14 and renders some changes as unnecessary in PR #53.
> Deploy via ssh

- crossbuilder
In the [nuntium](https://github.com/ubports/nuntium)'s repository crossbuilder instructions, there are multiple sources passed to the ```crossbuilder inst-foreign``` command, which doesn't work with current crossbuilder instance, cause only 1 source is allowed.
These changes make it possible to install multiple sources at once.
Or is there any reason, they were disallowed? Cause the ```install_foreign``` function did allow to install multiple sources, but the checks for the command were allowing only one source and only first souce was passed to the function.
> Allow passing multiple sources when using the inst-foreign command

- crossbuilder
While the /usr/local/bin trick works for crossbuilding, unfortunately
it breaks running tests for native builds. Since it's not needed for
native builds anyway, let's skip it there.
> install_dependencies: don't muck with Qt config for native build

- crossbuilder
Apt in newer Ubuntu won't install from unsigned, local repo by default.
To let it install, add `[trusted=yes]` in sources.list. This is the same
thing we do in  #38, but now on the device instead of in the container.
> Also use [trusted=yes] for deploying to devices

- crossbuilder
In ubuntu scinse focal lxd is only snap packages. But script check availability of apt-get and can't install lxd
> Make snap more priority

- crossbuilder
Due to the way our CI works, the version in the changelog will usually be bumped with `+0`. So, to combat with that, bump ours to `+1`.
This is particularly important when working with a library. When other packages are built against this one, dpkg-shlibdeps embeds the version of this package as seen in the CI. If we don't get this package's version to be higher, apt will start removing those packages installed on the phone.
> Bump version with +1 in front

- crossbuilder
New version of Ubuntu LXD images seem to have a slightly different sources line. Account for those by making the trailing slash optional.
Fixes: https://github.com/ubports/crossbuilder/issues/71
> nonsdk_container_setup: correct sources line changing

- crossbuilder
- nonsdk_container_setup: pull aptly_archive name from ut-version-info
- create_container: workaround privileged container + newer systemd 
- nonsdk_container_setup: support ports.u.c fixup for Deb822 (.sources) (fix crossbuilding)
- nonsdk_container_setup: for Debian, also consider alias (e.g. testing)
- nonsdk_container_fixup: do the ports.u.c fixup on Ubuntu only
Fixes: https://github.com/ubports/crossbuilder/issues/80
> Changes for Noble

- crossbuilder
to use crossbuilder script on fedora fc40, the return value of gcc -dumpmachine is simply x86_64-redhat-linux
> add support to build on fedora host

- crossbuilder
At some point the crossbuilder script does a ping to see if the connected device has got a working internet connection. Why does it need to ping google.com and link all out devices to google? I suggest using ubports.com, of any other privacy friendly solution. Suggestions welcome.
> replace google.com with ubports.com for pinging
